spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      # Каналы для Pub/Sub механизма Redis
      channels:
        user-banner-event: "app:user:banner"
        follower-event: "app:user:follower"
        mentorship-event: "app:user:mentorship"
        premium-bought-event: "app:user:premium:bought"
        profile-view-event: "app:user:profile:view"
        profile-appeared-in-search-event: "app:user:profile:appeared-in-search"

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    bucket-name: user-service-bucket
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    isMocked: false

task:
  scheduling:
    cron: &daily "0 0 0 * * *"

cleanUpPremiumRepo:
  cron: *daily

clearEvents:
  cron: "0 0 10 * * *"
  batchSize: 100

dicebear:
  pic-base-url-small: https://api.dicebear.com/7.x/bottts/svg?size=64&seed=
  pic-base-url: https://api.dicebear.com/7.x/bottts/svg?size=256&seed=

premium:
  remover:
    cron: "0 0 0 * * MON"
    batchSize: 100

executorConfig:
  thread-pool-size: 10